application: zhou-rongyu
version: 1
runtime: python
api_version: 1

default_expiration: "10d"
handlers:

- url: /favicon\.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon.ico
  mime_type: image/x-icon
  
- url: /static
  static_dir: static

- url: .*
  script: zstart.py
